"""add event_id to wear_log

Revision ID: 9a40a7204ce8
Revises: 
Create Date: 2026-01-01 10:46:53.117004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a40a7204ce8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wear_log', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_wear_log_event_id'), 'wear_log', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wear_log_event_id'), table_name='wear_log')
    op.drop_column('wear_log', 'event_id')
    # ### end Alembic commands ###
