"""add wear_log_current_cost_per_use

Revision ID: f2ca76fbe4ec
Revises: 41314018cdbe
Create Date: 2026-01-25 12:04:45.932201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ca76fbe4ec'
down_revision: Union[str, Sequence[str], None] = '41314018cdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wear_log', sa.Column('current_cost_per_use', sa.Float(), nullable=True))
    op.alter_column('wear_log', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wear_log', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('wear_log', 'current_cost_per_use')
    # ### end Alembic commands ###
